name: Release

on: [push]

jobs:
  build-cli:
    name: Build CLI
    runs-on: windows-2019
    strategy:
      matrix:
        nim: ["1.6.0"]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\.nimble
          key: ${{ runner.os }}-nimble-${{ matrix.nim-version}}-${{ hashFiles('paste2vrchat.nimble') }}
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "1.6.0"

      - name: Build CLI
        run: |
          nimble install --depsOnly -y
          nim c -d:release -d:strip --opt:size --app:gui --outdir:. cli/*.nim
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: |
            ./p2vrc_cli.exe
          args: "-9"

  build-addons:
    name: Build Addons
    runs-on: ubuntu-20.04
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: addons/yarn.lock
      - name: Yarn install
        run: |
          cd addons
          yarn install
      - name: Build
        run: |
          cd addons
          yarn build
