name: Release

on: [push]

jobs:
  build-cli:
    name: Build CLI
    runs-on: ubuntu-20.04
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build CLI
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu

  build-addons:
    name: Build Addons
    runs-on: ubuntu-20.04
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: addons/yarn.lock
      - name: Yarn install
        run: |
          cd addons
          yarn install
      - name: Build
        run: |
          cd addons
          yarn build
